apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb
  name: web-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  type: NodePort
  selector:
    app: myweb
status:
  loadBalancer: {}
